version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: always
    volumes:
    - /var/jenkins_home:/var/jenkins_home
    ports:
    - 8080:8080
    #working_dir: /app
